# .github/workflows/pr-template.yml
name: Set PR Template

on:
  pull_request:
    types: [opened]

jobs:
  set-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Hotfix Template
        if: startsWith(github.head_ref, 'hotfix/') || startsWith(github.head_ref, 'fix/')
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const hotfixTemplate = fs.readFileSync('.github/pr_templates/hotfix.md', 'utf8');
            
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              body: hotfixTemplate
            });